services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_VPN_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_VPN_ADDRESS}
      - SERVER_CITIES=${GLUETUN_CITY}
